--insert into Usuario values('u1','u1@a.com','u1');
--insert into Usuario values('u2','u2@a.com','u2');
--insert into Usuario values('u3','u3@a.com','u3');
--insert into Usuario values('u4','u4@a.com','u4');
--"select * from Uusuario where (nick=$nick) AND (password=$password)" //LOGIN
--insert into Tweet values($nick,$texto,'{"a":1996,"m":12,"d":19,"h":15,"min":0,"s":50}');//TWITTEAR
--select * from Tweet where nick=$nick ORDER BY instante DESC;//TweetsDeUsuario
--insert into Seguidores values('u1','u2');
--insert into Seguidores values('u1','u3');
--insert into Seguidores values('u1','u5');
--insert into Seguidores values('u5','u1');
--insert into Tweet values ('u1','hola');
--insert into Tweet values ('u5','Hello everyone');
